version: '3.3'
services:
  backend:
    image: brokenspere/234-project:latest
    ports:
      - "8085:8080"
    
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "8086:80"   
    volumes:
     - type: bind
       source: ./Project234
       target: /usr/share/nginx/html/assets